#!/bin/sh

LTIZE=
case `uname` in
    Darwin*) LTIZE=glibtoolize;;
    *) LTIZE=libtoolize;;
esac

aclocal &&
    $LTIZE --automake &&
    automake --gnu --add-missing &&
    autoconf &&
    autoreconf -i &&
    ./configure &&
    make clean &&
    make &&
    mvn test install
